const routes = {
    home: '/BookTour',
    profile: '/profile',
    search: '/search',
    destination: '/destination',
    destination_detail: '/destination/:id',
    tour: '/tour',
    tour_detail: '/tour/:id',
    blog: '/blog',
    blog_detail: '/blog-detail',
    contact: '/contact',
    about_us: '/about-us',
    team: '/team',
    team_detail: '/team-detail',
    error_404: '*',
    gallery: '/gallery',
    login: '/login',
    payment: '/payment',
    order: '/order',
    //Admin
    admin: '/admin',
    admin_account: '/admin-account',
    admin_account_detail: '/admin-account/:id',
    admin_tour: '/admin-tour',
    admin_tour_detail: '/admin-tour/:id',
    admin_destination: '/admin-destination',
    admin_destination_detail: '/admin-destination/:id',
    admin_blog: '/admin-blog',
    admin_blog_detail: '/admin-blog/:id',
    admin_blog_create: '/admin-blog-create',
    admin_contact: '/admin-contact',
    admin_contact_detail: '/admin-contact/:id',
};

export default routes;
